### ISSUE TITLE
KPIs admin/login page failed

### ISSUE THREAD

**Issue by wk0206** [okgreece/KPIs#1]
After I clone this repository to local, and install it(referenced http://kpi.okfn.gr/#_4gp85yc4ddkj).
I can visit http://127.0.0.1:8000, every tag seems correct.
But I can not visit http://127.0.0.1:8000/Admin(or localhost:9000/admin)

3Error

> ErrorException in UrlGenerator.php line 304:
Route [register] not defined. (View: /home/wang/OP/kpis/resources/themes/default/views/layouts/app.blade.php) (View: /home/wang/OP/kpis/resources/themes/default/views/layouts/app.blade.php)

> ErrorException in UrlGenerator.php line 304:
Route [register] not defined. (View: 

> InvalidArgumentException in UrlGenerator.php line 304:
Route [register] not defined.

**Comment by skarampatakis** [comment]
This should be fixed now by https://github.com/okgreece/KPIs/commit/5ab08d71221287e93c3c969acad64d5cd1ecae47. Please follow the install instructions on https://github.com/okgreece/KPIs/blob/master/readme.md because the one you mentioned are a bit outdated. Please inform if you have any other problem.
