### ISSUE TITLE
add organization error

### ISSUE THREAD

**Issue by wk0206** [okgreece/KPIs#2]
I can log in to the admin panel now.
The situation is like this.

- I can not add any organizations, even it is in the drop down list. It will go directly to error page with error

> ErrorException in OrganizationsController.php line 100:
Undefined offset: 0

- I can add codelist, but the codelists are too many, could you make a search function.

- I can add/edit aggregators, indicators, but I can not see any difference in the Dashboard.

Above all, the sequence of import data is quite confused for me, could you provide a little bit detailed instruction on how to import an dataset from triple store and show it in DashBoard?

my .env

> APP_ENV=local
APP_KEY=base64:77OgH/oKeS0eg4yCcTPDZhmwYExYb7+eVhOXlBGfpo4=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://localhost
APP_THEME=default
REGISTRATION_ENABLED=false
VALUE_CACHE=true
CACHE_TIME=120
LANG_DETECTOR_LANGUAGES=en,el

> DB_CONNECTION=sqlite

> BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

> ENDPOINT="http://data.openbudgets.eu/sparql"
RUDOLF=http://eis-openbudgets.iais.fraunhofer.de/api/3/cubes/
INDIGO=http://apps.openbudgets.eu/
INDIGO_ROUTE=#indigo/cube/analytics/
OS_VIEWER=http://eis-openbudgets.iais.fraunhofer.de/viewer/
GEONAMES_ENDPOINT="http://factforge.net/repositories/ff-news?infer=false&sameAs=false&"

**Comment by skarampatakis** [comment]
I would suggest to first change your APP_THEME to obeu. Then when you add a new organization from the list you a selction box will be shown to define if your organization is linked to a Geonames instance or not. For all obeu datasets the latter is the case so choose no. Then you will be guided to select the proper geonames instance. 

I agree that the workflow to have a new indicator is a bit complicated but it could not be less than that. Thw whole idea is to create mappings of codelists collections to Aggregators Superclass in order to achieve comparable results, at least at some point. You have to define such mappings for each codelist on the different datasets.

But please create separate issues for these in order to have better understanding of your situation. 

I will try to create a more detailed documentation on how to create indicators since the current is outdated.
